apiVersion: noderesources.dpu.nvidia.com/v1alpha1
kind: NodeSRIOVDevicePluginConfig
metadata:
  name: <SRIOV_DP_CONFIG_CR_NAME>
  namespace: dpf-operator-system
spec:
  devicePluginResources:
    - name: <SRIOV_DP_MGMT_POOL_NAME>
      type: vf
      ranges:
        - pfIndex: 0
          start: 1
          end: 1
    - name: <SRIOV_DP_CONFIG_NAME>
      type: vf
      options:
        isRdma: true
      ranges:
        - pfIndex: 0
          start: <PF0_REGULAR_VF_START>
          end: <PF0_REGULAR_VF_END>
        - pfIndex: 1
          start: <PF1_REGULAR_VF_START>
          end: <PF1_REGULAR_VF_END>
    <KATA_SRIOV_POOL>
